
package com.beitie.webservicebeitie.impl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "UseInfoServiceImplService", targetNamespace = "http://impl.webserviceBeiTie.beitie.com/", wsdlLocation = "http://127.0.0.1:12345/userInfo?wsdl")
public class UseInfoServiceImplService
    extends Service
{

    private final static URL USEINFOSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException USEINFOSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName USEINFOSERVICEIMPLSERVICE_QNAME = new QName("http://impl.webserviceBeiTie.beitie.com/", "UseInfoServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://127.0.0.1:12345/userInfo?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        USEINFOSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        USEINFOSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public UseInfoServiceImplService() {
        super(__getWsdlLocation(), USEINFOSERVICEIMPLSERVICE_QNAME);
    }

    public UseInfoServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), USEINFOSERVICEIMPLSERVICE_QNAME, features);
    }

    public UseInfoServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, USEINFOSERVICEIMPLSERVICE_QNAME);
    }

    public UseInfoServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, USEINFOSERVICEIMPLSERVICE_QNAME, features);
    }

    public UseInfoServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UseInfoServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns UseInfoServiceImpl
     */
    @WebEndpoint(name = "UseInfoServiceImplPort")
    public UseInfoServiceImpl getUseInfoServiceImplPort() {
        return super.getPort(new QName("http://impl.webserviceBeiTie.beitie.com/", "UseInfoServiceImplPort"), UseInfoServiceImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UseInfoServiceImpl
     */
    @WebEndpoint(name = "UseInfoServiceImplPort")
    public UseInfoServiceImpl getUseInfoServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://impl.webserviceBeiTie.beitie.com/", "UseInfoServiceImplPort"), UseInfoServiceImpl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (USEINFOSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw USEINFOSERVICEIMPLSERVICE_EXCEPTION;
        }
        return USEINFOSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
