server:
  port: 11001
spring:
  application:
    name: gateway_server
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  #开启从注册中心动态创建路由功能，利用服务名进行路由
      routes:
        - id: provider-service
#          uri: http://localhost:8080
          uri: lb://microservicecloud-dept-provider
          predicates:
            - Path=/product/*
          filters:
            - name: Hystrix
              args:
                name: default
                fallbackUri: forward:/defaultFallback
        - id: consumer-service
#          uri: http://localhost
          uri: lb://microservice-consumer
          predicates:
            - Path=/consumer/*
          filters:
            - name: Hystrix
              args:
                name: default
                fallbackUri: forward:/defaultFallback
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
          thread:
            timeoutInMilliseconds: 3000
  shareSecurityContext: true


eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: gateway_server11001
logging:
  level:
    org.springframework.cloud.gateway: debug
