server:
  port: 95271s1

spring:
  application:
    name: microservicecloud-zull
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
  instance:
    instance-id: microservicecloud-zuul-9527
    prefer-ip-address: true

info:
  app.name: microservice_dept_provider8080
  company.name: 深圳市红旗信息技术有限公司
  artifactId: ${project.artifactId}
  version: ${project.version}

zuul:
  routes:
    aaa.serviceId: microservicecloud-dept-provider
    aaa.path:  /mydept/**
  ignored-services: microservicecloud-dept-provider # "*"代表忽略所有的微服务
  prefix: /beitie
