server:
  port: 7001
eureka:
  instance:
    hostname: eureka7001.com
  client:
    register-with-eureka: false  #不想注册中心注册自己
    fetch-registry: false         #表明自己就是注册中心，负责维护服务实例，并不需要检索本服务

---
server:
  port: 7002
eureka:
  instance:
    hostname: eureka7002.com
  client:
    register-with-eureka: false  #不想注册中心注册自己
    fetch-registry: false         #表明自己就是注册中心，负责维护服务实例，并不需要检索本服务