spring:
  profiles:
    active:
      - dev
  application:
    name: microservicecloud-config-client
---
server:
  port: 8201
spring:
  profiles: dev

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka

---
server:
  port: 8202
spring:
  profiles: test

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
