spring:
  profiles:
    active:
      - dev
  application:
    name: microservicecloud-config-client
config:
  info: 'peizhixinxi wei version 444'
---
spring:
  profiles: dev

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka

---
spring:
  profiles: test

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
