/*
 * $Id: BizTrack.java 3996 2010-10-18 06:56:46Z lcj $
 * 
 * Copyright 2007-2008 RedFlagSoft.CN All Rights Reserved.
 * RedFlagSoft PROPRIETARY/CONFIDENTIAL.
 */
package cn.redflagsoft.base.bean;

import org.opoo.ndao.Domain;

/**
 * BizTrack generated by hbm2java
 */
public class BizTrack extends VersionableBean implements Domain<Long> {
	/**
	 * 
	 */
	private static final long serialVersionUID = -3160382046549511985L;
	private Long sn;
	private byte category;
	private Long bizSN;
	private String name;
	private String abbr;
	private byte sectNum;
	private byte stepNum;
	private byte nodeNum;

	public BizTrack() {
	}

	/**
	 * 唯一标示
	 * 
	 * @return Long
	 */
	public Long getId() {
		return getSn();
	}
	
	/**
	 * @param id
	 */
	public void setId(Long id) {
		setSn(id);
	}

	/**
	 * 唯一标示
	 * 
	 * @return Long
	 */
	public Long getSn() {
		return sn;
	}

	/**
	 * @param sn
	 */
	public void setSn(Long sn) {
		this.sn = sn;
	}

	/**
	 * 分类
	 * 
	 * 分类：1 作业：2 任务：3 工作
	 * @return byte
	 */
	public byte getCategory() {
		return category;
	}

	/**
	 * @param category
	 */
	public void setCategory(byte category) {
		this.category = category;
	}

	/**
	 * 业务编号
	 * 
	 * 具体业(作业或任务或工作)编号.
	 * @return Long
	 */
	public Long getBizSN() {
		return bizSN;
	}

	/**
	 * @param bizSN
	 */
	public void setBizSN(Long bizSN) {
		this.bizSN = bizSN;
	}

	/**
	 * 名称
	 * 
	 * 流程名称
	 * @return String
	 */
	public String getName() {
		return name;
	}

	/**
	 * @param name
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * 简称
	 * 
	 * 流程简称.
	 * @return String
	 */
	public String getAbbr() {
		return abbr;
	}

	/**
	 * @param abbr
	 */
	public void setAbbr(String abbr) {
		this.abbr = abbr;
	}

	/**
	 * 段数
	 *  
	 * 默认为0,表示未定义.
	 * @return byte
	 */
	public byte getSectNum() {
		return sectNum;
	}

	/**
	 * @param sectNum
	 */
	public void setSectNum(byte sectNum) {
		this.sectNum = sectNum;
	}

	/**
	 * 级数
	 *  
	 * 默认为0,表示未定义.
	 * @return byte
	 */
	public byte getStepNum() {
		return stepNum;
	}

	/**
	 * @param stepNum
	 */
	public void setStepNum(byte stepNum) {
		this.stepNum = stepNum;
	}

	/**
	 * 节点数
	 *  
	 * 默认为0,表示未定义.
	 * @return byte
	 */
	public byte getNodeNum() {
		return nodeNum;
	}

	/**
	 * @param nodeNum
	 */
	public void setNodeNum(byte nodeNum) {
		this.nodeNum = nodeNum;
	}

	
}
