server:
  port: 8080

mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  type-aliases-package: com.beitie.entity
  mapper-locations: classpath:mybatis/mapper/**/*.xml
spring:
  application:
    name: microservicecloud-dept-provider
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springcloud?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: bestbnf
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-idle: 200
      max-wait-millis: 200
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
  instance:
    instance-id: microservicecloud-dept-provider-hystrix8080
    prefer-ip-address: true

info:
  app.name: microservice_dept_provider8080
  company.name: 深圳市红旗信息技术有限公司
  artifactId: ${project.artifactId}
  version: ${project.version}
