dubbo:
          application:
            name: service_consumer
          registry:
            address: zookeeper://127.0.0.1:2181
          monitor:
            protocol: registry
          consumer:
            check: true
          server:
            port: 8080