server:
  port: 80
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
    register-with-eureka: true
  instance:
    instance-id: microservice_consumer80
spring:
  application:
    name: microservice_consumer
  zipkin:
    base-url: http://localhost:9411/
    sleuth:
      sampler:
        probablity: 1

