server:
  port: 80
#eureka:
#  client:
#    service-url:
#      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
#    register-with-eureka: true
#  instance:
#    instance-id: microservice_consumer80
spring:
  application:
    name: microservice_consumer
  zipkin:
    base-url: http://localhost:9090
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: microservicecloud-dept-consumer-consul

