mybatis:
  mapper-locations: classpath:mapper/**/*Mapper.xml
  type-aliases-package: com.beitie.springboot_quick001.entity
  config-location: classpath:mybatis/mybatis-config.xml
spring:
  datasource:
    username: root
    password: bestbnf
    url: jdbc:mysql://localhost:3306/springcloud2?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-idle: 200
      max-wait-millis: 200
 # redis:
 #   host: 192.168.220.131
  #  port: 6379
   # password: bestbnf

  redis:
    password: bestbnf
    cluster:
      # 各 Redis 节点信息
      nodes: 192.168.220.131:7001,192.168.220.131:7002,192.168.220.131:7003,192.168.220.131:7004,192.168.220.131:7005,192.168.220.131:7006
      # 执行命令超时时间
      command-timeout: 15000
      # 重试次数
      max-attempts: 5
      # 跨集群执行命令时要遵循的最大重定向数量
      max-redirects: 3
      # 连接池最大连接数（使用负值表示没有限制）
      max-active: 16
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1
      # 连接池中的最大空闲连接
      max-idle: 8
      # 连接池中的最小空闲连接
      min-idle: 0
      # 是否在从池中取出连接前进行检验,如果检验失败,则从池中去除连接并尝试取出另一个
      test-on-borrow: true

info:
  app.name: microservice_dept_provider8080
  company.name: 深圳市红旗信息技术有限公司
  artifactId: ${project.artifactId}
  version: ${project.version}

