/*
 * $Revision: 235 $
 *
 */
package org.opoo.apps.dvi.office.model;

import java.io.Serializable;

import org.opoo.apps.dvi.office.OfficeConversionArtifact;
import org.opoo.apps.dvi.office.OfficeConversionArtifactType;

/**
* A binary object (PDF, SWF, etc) generated by the conversion process.  This object is used for tracking purposes only.
* Binary data is stored in a separate storage provider, tracked by a key generated by this class.
*/
public class OfficeArtifact implements OfficeConversionArtifact, Serializable {
	private static final long serialVersionUID = 8812889530816115252L;
	//private static final Logger log = LogManager.getLogger(ConversionArtifact.class);
    private OfficeConversionArtifactType type;
    private String instanceID;
    private long conversionMetadataID;
    private int page = 0;
    private String filename;
    private String contentType;
    private long length;

    /**
     * Constructor for serialization use only.
     */
    public OfficeArtifact() {}

    /**
     * Constructor used to create key.
     * @param conversionMetadataID
     * @param type
     * @param page
     */
    public OfficeArtifact(long conversionMetadataID, OfficeConversionArtifactType type, int page) {
      
        this.instanceID = "NA";//JiveGlobals.getJiveProperty(JiveGlobals.JIVE_INSTANCE_ID);
        this.conversionMetadataID = conversionMetadataID;
        this.page = page;
        this.type = type;
    }

    /**
     * Constructor used by DAO.
     *
     * @param instanceID
     * @param conversionMetadataID

     * @param type
     * @param length
     * @param filename
     * @param contentType
     * @param page
     */
    public OfficeArtifact(String instanceID, long conversionMetadataID,
    		OfficeConversionArtifactType type, long length, String filename, String contentType, int page)
    {
        this.type = type;
        this.length = length;
        this.filename = filename;
        this.instanceID = "NA";//instanceID;
        this.conversionMetadataID = conversionMetadataID;
        this.contentType = contentType;
        this.page = page;
    }
   
    /**
     * This is the key we will use to retrieve this object from the StorageService.  It should be unique in a
     * system.
     *
     * @return a key which can be used to retrieve this object from the storage service.
     */
    public String getStorageKey() {
        return String.format("i%s_r%d_t%s_p%d", instanceID, conversionMetadataID, type.getName(), page);
    }

    public String getInstanceID() {
        return instanceID;
    }

    public long getConversionMetadataID() {
        return conversionMetadataID;
    }

    public int getPartNumber() {
        return page;
    }
    
    public int getPage(){
    	return page;
    }

    public OfficeConversionArtifactType getType() {
        return type;
    }

    public String getFilename() {
        return filename;
    }

    public String getContentType() {
        return contentType;
    }

    public long getLength() {
        return length;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }

        OfficeArtifact that = (OfficeArtifact) o;

        if (page != that.page) {
            return false;
        }
        if (conversionMetadataID != that.conversionMetadataID) {
            return false;
        }
        if (instanceID != null ? !instanceID.equals(that.instanceID) : that.instanceID != null) {
            return false;
        }
        if (type != that.type) {
            return false;
        }

        return true;
    }

    @Override
    public int hashCode() {
        int result = type != null ? type.hashCode() : 0;
        result = 31 * result + (instanceID != null ? instanceID.hashCode() : 0);
        result = 31 * result + (int) (conversionMetadataID ^ (conversionMetadataID >>> 32));
        result = 31 * result + page;
        return result;
    }

    @Override
    public String toString() {
        return "OfficeArtifact{" + "type=" + type + ", instanceID='" + instanceID + '\'' + ", revisionID="
                + conversionMetadataID + ", page=" + page + ", filename='" + filename + '\'' + ", contentType='" + contentType
                + '\'' + ", length=" + length + '}';
    }

    
    
    
    
    //用做实体类，需要ID属性和set方法。
    private long id;

	public long getId() {
		return id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public void setType(OfficeConversionArtifactType type) {
		this.type = type;
	}

	public void setInstanceID(String instanceID) {
		this.instanceID = instanceID;
	}

	public void setConversionMetadataID(long conversionMetadataID) {
		this.conversionMetadataID = conversionMetadataID;
	}

	public void setPage(int page) {
		this.page = page;
	}

	public void setFilename(String filename) {
		this.filename = filename;
	}

	public void setContentType(String contentType) {
		this.contentType = contentType;
	}

	public void setLength(long length) {
		this.length = length;
	}
}
