server:
  port: 7071

mybatis:
  type-aliases-package: com.beitie.bean
  mapper-locations: classpath:mapper/*Mapper.xml
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/beitielove?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: bestbnf
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    view:
      prefix: /WEB-INF/page/
      suffix: .jsp
