server:
  port: 8002
spring:
  application:
    name: springcloud2_payModule
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/springcloud3?useUnzicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: bestbnf
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-idle: 200
      max-wait-millis: 200
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  type-aliases-package: com.beitie.entity
  mapper-locations: classpath:mybatis/mapper/**/*.xml

