server:
  port: 11000
spring:
  application:
    name: gateway_server
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: provider_service
          uri: http://localhost:8080
          predicates:
            - Path=/product/*
          filters:
            - AddRequestParameter=foo,bar
        - id: consumer_service
          uri: http://localhost
          predicates:
            - Path=/consumer/*
          filters:
            - AddRequestParameter=foo,bar

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
logging:
  level:
    org.springframework.cloud.gateway: debug
