-------------------------------------------------------
-- hsqldb database schema
--
-- hsqldb 1.8.0.7
-------------------------------------------------------


CREATE TABLE SEC_USERS (
USERNAME VARCHAR(50) NOT NULL PRIMARY KEY,
PASSWORD VARCHAR(50) NOT NULL,
ENABLED BOOLEAN NOT NULL,
ACCOUNT_EXPIRE_TIME DATETIME,
ACCOUNT_NON_LOCKED BOOLEAN,
CREDENTIALS_EXPIRE_TIME DATETIME,
LAST_LOGIN_TIME DATETIME,
LOGIN_COUNT INT DEFAULT 0,
TRY_LOGIN_COUNT INT DEFAULT 0,
USERID BIGINT NOT NULL,
LOGIN_ADDRESS VARCHAR(150),
ONLINE_STATUS INT DEFAULT 0,
MTIME DATETIME,
CTIME DATETIME,
CREATOR VARCHAR(50),
MODIFIER VARCHAR(50)
);
 

CREATE TABLE SEC_UA(
ID BIGINT NOT NULL PRIMARY KEY,
USERNAME VARCHAR(50) NOT NULL,
AUTHORITY VARCHAR(50) NOT NULL,
FOREIGN KEY(USERNAME) REFERENCES SEC_USERS(USERNAME) ON DELETE CASCADE
);   

CREATE UNIQUE INDEX IX_UA ON SEC_UA(USERNAME, AUTHORITY);



CREATE TABLE SEC_GROUPS(
ID BIGINT NOT NULL PRIMARY KEY,
NAME VARCHAR(50) NOT NULL
);

CREATE UNIQUE INDEX IX_GOUPS_NAME ON SEC_GROUPS(NAME);


CREATE TABLE SEC_GA(
ID BIGINT NOT NULL PRIMARY KEY,
GROUPID BIGINT NOT NULL,
AUTHORITY VARCHAR(50) NOT NULL,
FOREIGN KEY(GROUPID) REFERENCES SEC_GROUPS(ID) ON DELETE CASCADE
);
CREATE UNIQUE INDEX IX_GA ON SEC_GA(GROUPID, AUTHORITY);

CREATE TABLE SEC_GM(
ID BIGINT NOT NULL PRIMARY KEY,
GROUPID BIGINT NOT NULL,
USERNAME VARCHAR(50) NOT NULL,
FOREIGN KEY(GROUPID) REFERENCES SEC_GROUPS(ID) ON DELETE CASCADE,
FOREIGN KEY(USERNAME) REFERENCES SEC_USERS(USERNAME) ON DELETE CASCADE
);

CREATE UNIQUE INDEX IX_GM ON SEC_GM(GROUPID, USERNAME);







CREATE TABLE T_SYS_PROPERTY(
PROPNAME VARCHAR(500) NOT NULL, 
PROPVALUE VARCHAR(2000) NOT NULL,
PRIMARY KEY(PROPNAME)
);


CREATE TABLE T_SYS_ID(
ID VARCHAR(32),
CURR BIGINT DEFAULT 0,
STEP INT DEFAULT 1,
DESCRIPTION VARCHAR(50),
PRIMARY KEY(ID)
);


CREATE TABLE T_SYS_ATTACHMENT(
ID BIGINT,
FILE_NAME VARCHAR(100) NOT NULL,
CONTENT_TYPE VARCHAR(100),
FILE_TYPE VARCHAR(20) NOT NULL,
FILE_SIZE BIGINT DEFAULT 0,
FETCH_COUNT INT DEFAULT 0,
STORE_NAME VARCHAR(100) DEFAULT 'store0',
STORE_TIME DATETIME,
LOCATION VARCHAR(200),
READABLE_FORMAT VARCHAR(20),
PROTECTED_FORMAT VARCHAR(20),
PRIMARY KEY(ID)
);


CREATE TABLE SEC_USERS_PROP(
USERNAME VARCHAR(50) NOT NULL,
PROPNAME VARCHAR(50) NOT NULL,
PROPVALUE VARCHAR(200) NOT NULL,
PRIMARY KEY(USERNAME, PROPNAME),
FOREIGN KEY(USERNAME) REFERENCES SEC_USERS(USERNAME) ON DELETE CASCADE
);

CREATE TABLE SEC_GROUPS_PROP(
GROUPID BIGINT NOT NULL,
PROPNAME VARCHAR(50) NOT NULL,
PROPVALUE VARCHAR(200) NOT NULL,
PRIMARY KEY(GROUPID, PROPNAME),
FOREIGN KEY(GROUPID) REFERENCES SEC_GROUPS(ID) ON DELETE CASCADE
);



CREATE TABLE SYS_PROPS_LOCALE(
  NAME         VARCHAR(100)    NOT NULL,
  PROPVALUE    VARCHAR(4000)   NOT NULL,
  LOCALE       VARCHAR(100)    NOT NULL,
  PRIMARY KEY (NAME, LOCALE)
);

CREATE TABLE SYS_PROPS (
  NAME        VARCHAR(100)  NOT NULL,
  PROPVALUE   VARCHAR(4000) NOT NULL,
  PRIMARY KEY (NAME)
);

CREATE TABLE SYS_MODULES(
NAME VARCHAR(100) NOT NULL,
CREATIONTIME BIGINT NOT NULL,
MODIFICATIONTIME BIGINT NOT NULL,
DATA LONGVARBINARY,
PRIMARY KEY(NAME)
);



INSERT INTO SEC_USERS(USERNAME, PASSWORD, ENABLED, ACCOUNT_NON_LOCKED, USERID) VALUES('rfsa','202cb962ac59075b964b07152d234b70',TRUE,TRUE,-1);

INSERT INTO SEC_UA VALUES(1,'rfsa','ADMIN');
INSERT INTO SEC_UA VALUES(2,'rfsa','USER');
INSERT INTO SEC_UA VALUES(3,'rfsa','SYSTEM');
