server:
  port: 8002

mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  type-aliases-package: com.beitie.entity
  mapper-locations: classpath:mybatis/mapper/**/*.xml
spring:
  application:
    name: microservicecloud-dept-provider
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springcloud2?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: bestbnf
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-idle: 200
      max-wait-millis: 200
  zipkin:
    base-url: http://localhost:9411/
    sleuth:
      sampler:
        probablity: 1
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
  instance:
    instance-id: microservicecloud-dept-provider8002
    prefer-ip-address: true

info:
  app.name: microservice_dept_provider8002
  company.name: 深圳市红旗信息技术有限公司
  artifactId: microservicecloud-provider-8002
  version: 2.0-SNAPSHOT