dubbo:
  application:
    name: provider_service
  registry:
    address: 127.0.0.1:2181
    protocol: zookeeper
  protocol:
    name: dubbo
    port: 20881
  monitor:
    protocol: registry
  config-center:
    address: zookeeper://127.0.0.1:2181 
  metadata-report:
    address: zookeeper://127.0.0.1:2181
server:
  port: 9001
