server:
  port: 9090
spring:
  application:
    name: zipkinServer
  datasource:
    url: jdbc:mysql://localhost:3306/zipkin?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false&user=root&password=bestbnf
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: bestbnf
eureka:
  instance:
    instance-id: microservicecloud-zipkin-9090
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
